name: pytw-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.13
  - pip
  - pybind11
  - ipython
  - jupyterlab
  - notebook
  - pytest
  - numpy>=2.0
  - pandas>=2.0
  - numba>=0.61
  - bipartitepandas>=1.1.3
  - scipy>=1.14
  - pyamg>=5.0
  - qpsolvers>=4.0
  - statsmodels>=0.14
  - configargparse
  - matplotlib
  - tqdm
  - nbsphinx
  - pip:
      - sphinx-rtd-theme # Sphinx theme
      - pyarrow

# conda env create --file environment.yml
# conda env remove --name pytw-env
